// This file is automatically generated by vscode-react-native@0.3.2
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/Andrew/Coding/MineMeal/node_modules/react');
var {Component} = React;

var ReactNative = require('/Users/Andrew/Coding/MineMeal/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('/Users/Andrew/Coding/MineMeal/index.android.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('minemeal', appParameters);
});